# ===============================
# APPLICATION
# ===============================
spring.application.name=risknet-backend
server.port=8080


# ===============================
# POSTGRESQL DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/risknet
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# NEO4J
# ===============================
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=${NEO4J_PASSWORD}